// Grocery Store using VueJS/src/webPages/landingPage/components/SignUp.vue
<template>
  <section className="sign-up">
    <!--  Sign-up Information  -->
    <article>
      <p>$30 discount for your first order</p>
      <h3>Get top deals,latest trends, and more.</h3>
      <p>
        Join our mail subscription now to get updates on promotions and
        coupons.
      </p>
      <!--  Form for email  -->
      <form action="#" method="get">
        <!--  Input for email with validation -->
        <input required type="email" name="email" id="email" placeholder="Email Address" autoComplete="true" />
        <!--  button to submit the form -->
        <button type="submit" id="signup">Sign Up</button>
      </form>
    </article>

    <!-- Image for the sign-up section  -->
    <img src="../../../../public/Images/girl-email.png" alt="girl-email.png" />
  </section>
</template>

<script>
export default {
  name: "SignUp"
}
</script>
<style src="../landingPage styles/SignUp.css" scoped></style>

// Grocery Store Using React Native/src/components/LandingPage/components/signup.jsx
import {
  ImageBackground,
  Image,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Alert,
} from "react-native";
import React, { useState } from "react";

import styles from "../styles/signup";

export default function SignUp() {
  const [email, setEmail] = useState("");

  const validateEmail = () => {
    // Regular expression for a basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (emailRegex.test(email)) {
      Alert.alert("Email Registered", "Your subscription is successful.");
    } else {
      Alert.alert("Invalid Email", "Please enter a valid email address.");
    }
  };
  return (
    <View style={styles.container}>
      <ImageBackground
        source={require("../../../../assets/Images/pattern.png")}
        style={styles.backgroundImage}
      >
        <Text style={styles.text1}>$30 discount for your first order</Text>
        <Text style={styles.text2}>
          Get top deals, latest trends, and more.
        </Text>
        <Text style={styles.text3}>
          Join our email subscription now to get updates on promotions and
          coupons.
        </Text>
        <View style={styles.emailInput}>
          <TextInput
            style={styles.textInput}
            placeholder="Email Address"
            autoComplete="email"
            keyboardType="email-address"
            onChangeText={(text) => setEmail(text)}
          />
          <TouchableOpacity style={styles.button} onPress={validateEmail}>
            <Text style={styles.text4}>Sign Up</Text>
          </TouchableOpacity>
        </View>
        <Image source={require("../../../../assets/Images/girl-email.png")} />
      </ImageBackground>
    </View>
  );
}
