// Grocery Store using VueJS/src/webPages/addToCartPage/components/NavBar.vue
<template>
  <nav class="cart-navbar">
    <ul class="cart-navList">
      <li class="cart-navItem">
        <router-link to="/" class="cart-nav-link">Home /</router-link>
      </li>
      <li class="cart-navItem">
        <router-link to="/productList" class="cart-nav-link">Shop /</router-link>
      </li>
      <li class="cart-navItem">
        <router-link to="/cart" class="cart-nav-link">Cart</router-link>
      </li>
    </ul>
  </nav>
</template>
  
<script>
export default {
  data() {
    return {
    };
  },
};
</script>
  
<style src="../addToCart styles/addToCart.css" scoped></style>

// Grocery Store using ReactJS/src/components/navbar.jsx
// Navbar.js
import style from "../styles/cartstyles.module.css"
import React from 'react';
import { useNavigate } from "react-router-dom";


const Navbar = () => {

  const navigate = useNavigate();

  return (
    <nav className={style.navbar}>
      <ul className={style.nav_list}>
        <li className={style.nav_item}>
          <a onClick={() => navigate("/")} className={style.nav_link}>
            Home
          </a>
        </li>
        <li className={style.nav_item}>
          <a onClick={() => navigate("/productList")} className={style.nav_link}>
            Shop
          </a>
        </li>
        <li className={style.nav_item}>
          <a href="#cart" className={style.nav_link}>
            Cart
          </a>
        </li>
      </ul>
    </nav>
  );
};

export default Navbar;
