// Grocery Store using ReactJS/src/components/productItem.jsx
import React, { useEffect, useState } from 'react';
import '../styles/index.css';
import '../styles/mobile.css';
import { RiDeleteBin5Line } from "react-icons/ri";
import style from "../styles/cartstyles.module.css"
import { useDispatch, useSelector } from 'react-redux';
import { setItemQuantity, removeItem } from '../state/cart/cartSlice'; 

const ProductItem = ({ item }) => {

  const items = useSelector((state) => state.cart.items);
  const dispatch = useDispatch();

  const [quantity, setQuantity] = useState(items[item.id]);
  
  // console.log(item)

  const removeItemFromCart = () => {
    dispatch(removeItem(item.id)); 
  };

  const decreaseQuantity = () => {
    if (quantity > 0) {
      setQuantity(quantity - 1);
    }
  };

  const increaseQuantity = () => {
    if (quantity < 10) {
      setQuantity(quantity + 1);
    }
  };

  useEffect(() => {
    dispatch(setItemQuantity({
      id: item.id,
      quantity: quantity
    }));
  }, [quantity]);

  
    return (
      <li key={item.id} className={style.product_item}>
        <div className={style.product_image}>
          <img src={item.img[0]} alt="Ecommerce" />
        </div>
        <div className={style.product_details}>
          <a className={style.product_title}>{item.name}</a>
          <span className={style.product_price}>${item.price}</span>
          <div className={style.product_actions}>
          <div className={style.remove_container}  onClick={removeItemFromCart}>
            <RiDeleteBin5Line  className={style.delete_icon} />
            <span className={style.remove_text}>Remove</span>
          </div>
        </div>
        </div>
        <div className={style.quantity}>
          <button className={style.quantity_btn} onClick={decreaseQuantity}>-</button>
          <input  type="text"  value={quantity} readOnly className={style.quantity_input} step={1} max={10}  />
          <button className={style.quantity_btn} onClick={increaseQuantity}>+</button>
        </div>
        <div className={style.price}>
        <span className={style.price_value}>{`$${(quantity * item.price)}`}</span>
      </div>
      </li>
    );
  };
  
  export default ProductItem;

// Grocery Store using VueJS/src/webPages/addToCartPage/components/ProductItem.vue
<template>
  <li :key="item.id" class="productitem">
    <div class="productimage">
      <img :src="item.img[0]" alt="Ecommerce" />
    </div>
    <div class="productdetails">
      <a class="producttitle">{{ item.name }}</a>
      <span class="productprice">{{ `$${item.price}` }}</span>
      <div class="productactions">
        <div class="removecontainer" @click="removeItemFromCart">
          <font-awesome-icon icon="trash" />
          <span class="removetext">Remove</span>
        </div>
      </div>
    </div>
    <div class="quantity">
      <button class="quantitybtn" @click="decreaseQuantity">-</button>
      <input name="quantityInput" type="text" v-model="quantity"  class="quantityInput" step="1" />
      <button class="quantitybtn" @click="increaseQuantity">+</button>
    </div>
    <div class="price">
      <span class="pricevalue">{{ `$${calculatedPrice}` }}</span>
    </div>
  </li>
</template>

<script>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

export default {
  props: {
    item: Object,
  },

  data() {
    return {
      quantity: this.$store.state.cart.cartItems.find((i) => i.id === this.item.id)?.quantity || 1,
    };
  },

  computed: {
    calculatedPrice() {
      return (this.quantity * this.item.price).toFixed(2);
    },
  },

  methods: {
    removeItemFromCart() {
      this.$store.dispatch('cart/removeItem', this.item.id);
    },

    decreaseQuantity() {
      if (this.quantity > 0) {
        this.quantity--;
        this.updateCartItemQuantity();
      
        if (this.quantity === 0) {
        this.removeItemFromCart();
      }
      }
    },
    
    increaseQuantity() {
      if (this.quantity < 10) {
        this.quantity++;
        this.updateCartItemQuantity();
      }
    },

    updateCartItemQuantity() {
      this.$store.dispatch('cart/setItemQuantity', {
        id: this.item.id,
        quantity: this.quantity,
      });
    },
  },

  watch: {
    '$store.state.cart.cartItems': {
      handler(newCartItems) {
        // Handle the case when quantities are updated outside of the component
        const cartItem = newCartItems.find((i) => i.id === this.item.id);
        this.quantity = cartItem?.quantity || 1;
      },
      deep: true,
    },
  },

  components: {
    FontAwesomeIcon,
  },
};
</script>

<style src="../addToCart styles/addToCart.css" scoped></style>
