// Grocery Store using VueJS/src/webPages/addToCartPage/components/CartProduct.vue
<template>
  <div>
    <div class="container">
      <div>
        <!-- alert -->
        <div class="alert">
          You've got FREE delivery. Start <router-link to="/checkout" class="alert-link">checkout now!</router-link>
        </div>
        <ul class="product-list">
          <ProductItem v-for="key in itemKeys" :key="key" :item="findItemById(key)" />
        </ul>
        <br />
        <!-- buttons -->
        <div>
          <button @click="continueShopping" class="btn btncontinueshopping">Continue Shopping</button>
          <button @click="handleUpdateCart" class="btn btnupdate">Update Cart</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ProductItem from './ProductItem.vue';
import { mapState } from 'vuex';

export default {
  methods: {
    
    mounted() {
      this.$store.dispatch('cart/loadGroceryData');
    },

    findItemById(id) {
      for (const category of this.groceryData) {
        for (const item of category.items) {
          if (item.id == id) {
            return item;
          }
        }
      }
      return null;
    },

    handleUpdateCart() {
      
      this.$store.dispatch('cart/updateCart').then(() => {
        this.$store.commit('cart/setCartUpdated', true); 
        this.calculateSubTotal(); 
      });
    },

    continueShopping() {
      this.$router.push('/productList');
    },
    calculateSubTotal() {
      const items = this.$store.state.cart.cartItems;
      this.$store.commit('cart/setCartItems', items); 
      this.$store.dispatch('cart/updateCart'); // Update the cart
    },
  },

  computed: {
    ...mapState('cart', ['cartItems']),

    container() {
      return {
        [this.$style.container]: true,
      };
    },

    groceryData() {
      return require('../../../../public/assets/grocery.json');
    },


    itemKeys() {
      const items = this.$store.getters['cart/cartItemsWithDetails'];
      return items.map((item) => item.id);
    },

  },
  components: {
    ProductItem,
  },

  created() {
    this.$store.dispatch('cart/loadGroceryData');
  },
};
</script>

<style src="../addToCart styles/addToCart.css" scoped></style>

// Grocery Store Using React Native/src/components/CartPage/components/cartProduct.jsx

import React, { useEffect, useState } from 'react';
import { View, StyleSheet, Text, TouchableOpacity} from 'react-native';
import ProductItem from './productItem';
import { useDispatch, useSelector } from 'react-redux';
import groceryData from '../../../../assets/grocery.json';
import styles from '../styles/cart';
import { updateSubtotal } from '../../../state/cart/cartSlice'; 





function findItemById(id) {
  for (const category of groceryData) {
    for (const item of category.items) {
      if (item.id == id) {
        return item;
      }
    }
  }
  return null;
}

const CartProduct = ({ navigation }) => {
  const items = useSelector((state) => state.cart.items);
  const dispatch = useDispatch();
  const [subTotal, setSubTotal] = useState(0);

  useEffect(() => {
    let t = getSubtotal();
    // console.log('triggered' + t)
    setSubTotal(t);
  }, [items])

  const getSubtotal = () => {
    let subTotal = 0;
    Object.keys(items).forEach((key) => {
      let item = findItemById(key);
      subTotal += (item.price * items[key]);
    });
    return subTotal;
  }

  const handleUpdateCartClick = () => {
    let subtotal = getSubtotal();
    dispatch(updateSubtotal(subtotal));
  };

  const handleClick = () => {
    navigation.navigate("Product");
  };
  // console.log(items);

  return (
    <View style={styles.container}>
      {/* Alert */}
      <View style={styles.alertContainer}>
        <Text style={styles.alertText}>
          You've got FREE delivery. Start{' '}
          <Text style={styles.alertLink}>Checkout now!</Text>
        </Text>
      </View>

      {/* Product List */}
      <View style={styles.productList}>
        {Object.keys(items).map((key) => {
          let item = findItemById(key);
          return <ProductItem key={key} item={item} />;
        })}
      </View>

      {/* Buttons */}
      <View style={styles.buttonContainer}>
        <TouchableOpacity
          style={[styles.button, styles.continueShoppingButton]}
          onPress={handleClick}
        >
          <Text style={styles.buttonText}>Continue Shopping</Text>
        </TouchableOpacity>
        <TouchableOpacity style={[styles.button, styles.updateButton]} onPress={handleUpdateCartClick}>
          <Text style={styles.buttonText}>Update Cart</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};
 


export default CartProduct;
