// Grocery Store using VueJS/src/webPages/addToCartPage/components/ProductItem.vue
<template>
  <li :key="item.id" class="productitem">
    <div class="productimage">
      <img :src="item.img[0]" alt="Ecommerce" />
    </div>
    <div class="productdetails">
      <a class="producttitle">{{ item.name }}</a>
      <span class="productprice">{{ `$${item.price}` }}</span>
      <div class="productactions">
        <div class="removecontainer" @click="removeItemFromCart">
          <font-awesome-icon icon="trash" />
          <span class="removetext">Remove</span>
        </div>
      </div>
    </div>
    <div class="quantity">
      <button class="quantitybtn" @click="decreaseQuantity">-</button>
      <input name="quantityInput" type="text" v-model="quantity"  class="quantityInput" step="1" />
      <button class="quantitybtn" @click="increaseQuantity">+</button>
    </div>
    <div class="price">
      <span class="pricevalue">{{ `$${calculatedPrice}` }}</span>
    </div>
  </li>
</template>

<script>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

export default {
  props: {
    item: Object,
  },

  data() {
    return {
      quantity: this.$store.state.cart.cartItems.find((i) => i.id === this.item.id)?.quantity || 1,
    };
  },

  computed: {
    calculatedPrice() {
      return (this.quantity * this.item.price).toFixed(2);
    },
  },

  methods: {
    removeItemFromCart() {
      this.$store.dispatch('cart/removeItem', this.item.id);
    },

    decreaseQuantity() {
      if (this.quantity > 0) {
        this.quantity--;
        this.updateCartItemQuantity();
      
        if (this.quantity === 0) {
        this.removeItemFromCart();
      }
      }
    },
    
    increaseQuantity() {
      if (this.quantity < 10) {
        this.quantity++;
        this.updateCartItemQuantity();
      }
    },

    updateCartItemQuantity() {
      this.$store.dispatch('cart/setItemQuantity', {
        id: this.item.id,
        quantity: this.quantity,
      });
    },
  },

  watch: {
    '$store.state.cart.cartItems': {
      handler(newCartItems) {
        // Handle the case when quantities are updated outside of the component
        const cartItem = newCartItems.find((i) => i.id === this.item.id);
        this.quantity = cartItem?.quantity || 1;
      },
      deep: true,
    },
  },

  components: {
    FontAwesomeIcon,
  },
};
</script>

<style src="../addToCart styles/addToCart.css" scoped></style>

// Grocery Store Using React Native/src/components/CartPage/components/productItem.jsx

import React, { useEffect, useState } from 'react';
import { View, Text, Image, TouchableOpacity, TextInput, StyleSheet, Dimensions } from 'react-native';
import { useDispatch, useSelector } from 'react-redux';
import { setItemQuantity, removeItem } from '../../../state/cart/cartSlice'; 
import styles from '../styles/cart';
import Icon from 'react-native-vector-icons/FontAwesome';

const ProductItem = ({ item }) => {
  
  const items = useSelector((state) => state.cart.items);
  const dispatch = useDispatch();

  const [quantity, setQuantity] = useState(items[item.id]);

  const removeItemFromCart = () => {
    dispatch(removeItem(item.id)); 
  };

  const decreaseQuantity = () => {
    if (quantity > 0) {
      setQuantity(quantity - 1);
    }
  };

  

  const increaseQuantity = () => {
    if (quantity < 10) {
      setQuantity(quantity + 1);
    }
  };

  useEffect(() => {
    dispatch(setItemQuantity({
      id: item.id,
      quantity: quantity
    }));
  }, [quantity]);


  return (
    <View style={styles.productItem} key={item.id}>
    <View style={styles.productImage}>
      <Image source={{ uri: item.img[0] }} style={styles.image} />
    </View>
    <View style={styles.productDetails}>
      <Text style={styles.productTitle}>{item.name}</Text>
      <Text style={styles.productPrice}>${item.price}</Text>
      <View style={styles.productActions}>
        <TouchableOpacity style={styles.removeContainer} onPress={removeItemFromCart}>
          <Icon name="trash" style={styles.deleteIcon} />
          <Text style={styles.removeText}>Remove</Text>
        </TouchableOpacity>
      </View>
    </View>
    <View style={styles.quantity}>
      <TouchableOpacity style={styles.quantityBtn} onPress={decreaseQuantity}>
        <Text>-</Text>
      </TouchableOpacity>
      <TextInput
        style={styles.quantityInput}
        value={quantity.toString()}
        readOnly
        keyboardType="numeric"
        maxLength={10}
      />
      <TouchableOpacity style={styles.quantityBtn} onPress={increaseQuantity}>
        <Text>+</Text>
      </TouchableOpacity>
    </View>
    <View style={styles.price}>
      <Text style={styles.priceValue}>{`$${quantity * item.price}`}</Text>
    </View>
  </View>
    
  );
};



export default ProductItem;
