// Grocery Store using ReactJS/src/components/orderConfirmation.jsx
import React from 'react'
import '../styles/index.css'; 
import { useLocation } from 'react-router-dom';
import { useEffect } from 'react';
import { useState } from 'react';

const OrderConfirmation = () => {
  const location = useLocation();
  const addressType = new URLSearchParams(location.search).get('addressType');
  const firstName = new URLSearchParams(location.search).get('firstName');
  const address1 = new URLSearchParams(location.search).get('addressLine1');
  const email = new URLSearchParams(location.search).get('email');
  // const address2 = new URLSearchParams(location.search).get('addressLine2');

  const [token, setToken] = useState('');

  useEffect(() => {
    // Fetch the existing array from localStorage
    const storedOrderData = JSON.parse(localStorage.getItem('OrderData')) || [];
 
    // Generate a new token
    const num = Math.round(10000 * Math.random());
    const orderid = `#BM${num}`;
    setToken(orderid);
 
    // Append the new token to the existing array
    const newOrderData = [...storedOrderData, orderid];
    // setTokenArray(newOrderData);
 
    // Store the updated array in localStorage
    localStorage.setItem('OrderData', JSON.stringify(newOrderData));
 
    console.log('Generated Token:', orderid);
    console.log('Updated Array:', newOrderData);
  }, []);

  
  return (
    <div className="OrderConfirm">
        <h1>Checkout</h1>
        <div className="mainbox">
        <span><i className="fa-icon fa-regular fa-circle-check" style={{color: "#1f3951"}}></i></span>
        <div className="firstbox">
                <p className='order-text'>Order {token}</p>
                <h2>Thank you {firstName}</h2>
        </div>
        <div className='clear'></div>
        <div className='orderUpdates' style={{border: "2px solid lightgray", borderRadius: "5px", paddingLeft: "10px", marginTop: "1%"}}>
            <h2>Order Updates</h2>
            <p className="text-style">You will receive order and shipping updates via email</p>

        </div>
        <div className="blank-space">
        </div>
        <div className="table-content">
            <div className="inside-content">
            <p className='info-q'><strong>Contact</strong></p>
            <p>{email}</p>
            </div>
            <div className="inside-content">
            <p className='info-q'><strong>Address</strong></p>
            <div className="paras-for-add">
            <p>{address1} </p> 
            {/* <p> {address2} </p> */}
            </div>
            </div>
            <div className="inside-content">
            <p className='info-q'> <strong>Payment</strong></p>
            <p>Check Payments</p>
            </div>

            {/* <button onClick={pushValueIntoArray}>Submit</button> */}

        </div>
    </div>
    </div>
  )
}

export default OrderConfirmation

// Grocery Store using VueJS/src/webPages/orderConfirmationPage/components/orderConfirmation.vue
<template>
    <div class="OrderConfirm">
        <h1>Checkout</h1>
        <div class="mainbox">
            <span><font-awesome-icon icon="fa-regular fa-circle-check" /></span>
            <div class="firstbox">
                <p class='order-text'>Order {{ orderid }}</p>
                <h2>Thank you {{ addresses.firstName }} </h2>
            </div>

            <div class='orderUpdates'>
                <h2>Order Updates</h2>
                <p class="text-style">You will receive order and shipping updates via email</p>
            </div>
        </div>
        <div class="blank-space"></div>
        <div class="table-content">
            <div class="inside-content">
                <p class='info-q'><strong>Contact</strong></p>
                <p> {{ addresses.Email }} </p>
            </div>
            <div class="inside-content">
                <p class='info-q'><strong>Address</strong></p>
                <div class="paras-for-add">
                    <p> {{ addresses.addressLine1 }} , {{ addresses.addressLine2 }} , {{ addresses.state }} -
                        {{ addresses.zipCode }} </p>
                </div>
            </div>
            <div class="inside-content">
                <p class='info-q'><strong>Payment</strong></p>
                <p> {{ paymentMethod }} </p>
            </div>
        </div>
    </div>
</template>
  
<script>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

export default {
    name: 'OrderConfirmationComp',
    components: {
        FontAwesomeIcon,
    },
    data() {
        return {
            addresses: [],
            paymentMethod: "",
            orderid: null,
            paymentM: []
        }
    },
    //Accessing data from store
    mounted() {
        // console.log(this.$store.state.orderDetails.addresses);
        this.addresses = this.$store.state.orderDetails.addresses;
        //   console.log(this.addresses)
        //   console.log(this.$store.state.orderDetails.selectedPaymentMethod);
        this.paymentMethod = this.$store.state.orderDetails.selectedPaymentMethod;
        //   console.log(this.paymentMethod);
        this.orderid = "#BM" + Math.floor(1000 + Math.random() * 9000);
        const storedOrderData = JSON.parse(localStorage.getItem('OrderData')) || [];
        const storedPaymentData = JSON.parse(localStorage.getItem('PaymentData')) || [];
        const newOrderData = [...storedOrderData, this.orderid];
        const newPaymentData = [...storedPaymentData, this.paymentMethod];
        localStorage.setItem('OrderData', JSON.stringify(newOrderData));
        localStorage.setItem('PaymentData', JSON.stringify(newPaymentData));
    },
};
</script>
  
<style src="../orderConfirmation styles/orderConfirmation.css" scoped></style>
