// Grocery Store using ReactJS/src/components/orderdetail.jsx
import React from "react";
import CartSummary2 from "./cartSummary2";
import CartProduct2 from "./cartProducts2";
import style from "../styles/cartstyles.module.css"


const Orderdetail = () => {
    
  return (
     <div className={style.cart2} >
    <h3 >Order Details</h3>
      <div >
      <div className={style.cart_item}>
        <CartProduct2 />
      </div>
      <div className={style.cart_summary}>
        <CartSummary2 />
      </div>
    </div>
    </div>
    
  );
};

export {Orderdetail};

// Grocery Store using VueJS/src/webPages/checkoutPage/components/orderDetail.vue
<template >
  <div class="cart2">
    <h2>Order Details</h2>
    <cartProduct2 />
    <cartSummary2 />
  </div>
</template>

<script>
import cartProduct2 from './cartProduct2.vue';
import cartSummary2 from './cartSummary2.vue';

export default {
  components: {
    cartProduct2,
    cartSummary2
  }
}
</script>

<style src="../checkoutPage styles/checkoutPage.css" scoped></style>
